### PR TITLE
feat: replace gorilla/mux with labstack/echo

### LINKED ISSUE #275: Replace gorilla/mux with echo library
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for dependencies

### Description [**REQUIRED**]
According to the TSC decision, we should replace gorilla/mux with echo library.

### PR DESCRIPTION
**Pull request by FelixTing**
This commit refactors the RTSPCredentialsHandler method in the Driver struct from a standard HTTP handler function to an Echo framework handler function. The original function signature:

    func (d *Driver) RTSPCredentialsHandler(w http.ResponseWriter, r *http.Request)

has been updated to:

    func (d *Driver) RTSPCredentialsHandler(c echo.Context) error

closes #275 

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

Run `make docker` to build the image
From the latest compose-builder run `make run no-secty device-dev ds-usb-camera`
Verify the device-usb-camera service bootstraps successfully and contains the following log message:
```
level=INFO ts=2023-08-25T14:32:58.176008677Z app=device-usb-camera source=driver.go:217 msg="Starting rtsp authentication server on localhost:8000"

```
Follow the walkthrough(https://docs.edgexfoundry.org/3.0/microservices/device/supported/device-usb-camera/walkthrough/general-usage/) to play an RTSP stream.

### CODE REVIEW

**Comment by cloudxxx8** [comment]
the echo banner in the log should be hidden
https://github.com/labstack/echo/issues/928
https://echo.labstack.com/docs/customization#startup-banner

**Review by lenny-goodell — COMMENTED** [review]
LGTM, will defer to @ajcasagrande and team for final review.

**Review by seanohair22 — APPROVED** [review]
Tested, functions as expected with RTSP Server enabled and disabled. LGTM!

**Comment by lenny-goodell** [comment]
> Tested, functions as expected with RTSP Server enabled and disabled. LGTM!

@seanohair22 , thanks for testing!

**Review by lenny-goodell — APPROVED** [review]

**Pull request merged**
