### PR TITLE
fix: Fix StartStreaming command

### PR DESCRIPTION
**Pull request by FelixTing**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-examples/blob/master/.github/CONTRIBUTING.md.

## What is the current behavior?

- StartStreaming command will fail if users use the Pixel Format obtained by GetDataFormat command
- Users cannot see the error message if StartStreaming fails

## What is the new behavior?
- Add checks and conversions for the input Pixel Format value.
- If StartStreaming fails, the error message will be cached. To see the error message, use the StreamingStatus command.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports
Are there any new imports or modules? If so, what are they used for and why?

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

### CODE REVIEW

**Review by lenny-goodell — COMMENTED** [review]
LGTM, @surajitx-pal will this address the issues you observed?

**Comment by lenny-goodell** [comment]
@FelixTing , please rebase your PR so this fix is included.
https://github.com/edgexfoundry/device-usb-camera/pull/56

**Comment by FelixTing** [comment]
rebased

**Review by lenny-goodell — APPROVED** [review]
LGTM

**Pull request merged**
